displayName: TRIMM Redirects plugin

type: middleware

import: github.com/TRIMM/redirects-traefik-middleware

summary: "Redirect based on the entries received from the Central API."

testData:
  redirectsURL: "redirects-middleware:8080"
