// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: proto/request.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RedirectServiceClient is the client API for RedirectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedirectServiceClient interface {
	GetRedirectMatch(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type redirectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedirectServiceClient(cc grpc.ClientConnInterface) RedirectServiceClient {
	return &redirectServiceClient{cc}
}

func (c *redirectServiceClient) GetRedirectMatch(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/RedirectService/GetRedirectMatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedirectServiceServer is the server API for RedirectService service.
// All implementations must embed UnimplementedRedirectServiceServer
// for forward compatibility
type RedirectServiceServer interface {
	GetRedirectMatch(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedRedirectServiceServer()
}

// UnimplementedRedirectServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRedirectServiceServer struct {
}

func (UnimplementedRedirectServiceServer) GetRedirectMatch(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRedirectMatch not implemented")
}
func (UnimplementedRedirectServiceServer) mustEmbedUnimplementedRedirectServiceServer() {}

// UnsafeRedirectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedirectServiceServer will
// result in compilation errors.
type UnsafeRedirectServiceServer interface {
	mustEmbedUnimplementedRedirectServiceServer()
}

func RegisterRedirectServiceServer(s grpc.ServiceRegistrar, srv RedirectServiceServer) {
	s.RegisterService(&RedirectService_ServiceDesc, srv)
}

func _RedirectService_GetRedirectMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedirectServiceServer).GetRedirectMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RedirectService/GetRedirectMatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedirectServiceServer).GetRedirectMatch(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RedirectService_ServiceDesc is the grpc.ServiceDesc for RedirectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedirectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RedirectService",
	HandlerType: (*RedirectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRedirectMatch",
			Handler:    _RedirectService_GetRedirectMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/request.proto",
}
